[
    {
        "model":"A",
        "rotation":0,
        "sockets":[
            "1f",
            "-1",
            "-1",
            "v2_0",
            "-1",
            "1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"A",
        "rotation":1,
        "sockets":[
            "-1",
            "1",
            "-1",
            "v2_1",
            "-1",
            "1f"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"A",
        "rotation":2,
        "sockets":[
            "-1",
            "1f",
            "-1",
            "v2_2",
            "1",
            "-1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"A",
        "rotation":3,
        "sockets":[
            "1",
            "-1",
            "-1",
            "v2_3",
            "1f",
            "-1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"B",
        "rotation":0,
        "sockets":[
            "2",
            "-1",
            "-1",
            "v2_0",
            "2f",
            "-1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"B",
        "rotation":1,
        "sockets":[
            "-1",
            "2f",
            "-1",
            "v2_1",
            "-1",
            "2"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"B",
        "rotation":2,
        "sockets":[
            "-1",
            "2",
            "-1",
            "v2_2",
            "2f",
            "-1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"B",
        "rotation":3,
        "sockets":[
            "2f",
            "-1",
            "-1",
            "v2_3",
            "2",
            "-1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"C",
        "rotation":0,
        "sockets":[
            "3f",
            "-1",
            "v2_0",
            "v2_0",
            "-1",
            "3"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"C",
        "rotation":1,
        "sockets":[
            "-1",
            "3",
            "v2_1",
            "v2_1",
            "-1",
            "3f"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"C",
        "rotation":2,
        "sockets":[
            "-1",
            "3f",
            "v2_2",
            "v2_2",
            "3",
            "-1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"C",
        "rotation":3,
        "sockets":[
            "3",
            "-1",
            "v2_3",
            "v2_3",
            "3f",
            "-1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"D",
        "rotation":0,
        "sockets":[
            "1f",
            "-1",
            "-1",
            "v2_0",
            "-1",
            "2f"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"D",
        "rotation":1,
        "sockets":[
            "-1",
            "2f",
            "-1",
            "v2_1",
            "-1",
            "1f"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"D",
        "rotation":2,
        "sockets":[
            "-1",
            "1f",
            "-1",
            "v2_2",
            "2f",
            "-1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"D",
        "rotation":3,
        "sockets":[
            "2f",
            "-1",
            "-1",
            "v2_3",
            "1f",
            "-1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"E",
        "rotation":0,
        "sockets":[
            "4s",
            "-1",
            "-1",
            "v1_0",
            "1f",
            "1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"E",
        "rotation":1,
        "sockets":[
            "1f",
            "1",
            "-1",
            "v1_1",
            "-1",
            "4s"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"E",
        "rotation":2,
        "sockets":[
            "-1",
            "4s",
            "-1",
            "v1_2",
            "1",
            "1f"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"E",
        "rotation":3,
        "sockets":[
            "1",
            "1f",
            "-1",
            "v1_3",
            "4s",
            "-1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"F",
        "rotation":0,
        "sockets":[
            "4s",
            "4s",
            "-1",
            "-1",
            "4s",
            "4s"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"G",
        "rotation":0,
        "sockets":[
            "0",
            "-1",
            "v1_0",
            "v1_0",
            "3",
            "3f"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"G",
        "rotation":1,
        "sockets":[
            "3f",
            "3",
            "v1_1",
            "v1_1",
            "-1",
            "0"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"G",
        "rotation":2,
        "sockets":[
            "-1",
            "0",
            "v1_2",
            "v1_2",
            "3",
            "3f"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"G",
        "rotation":3,
        "sockets":[
            "3",
            "3f",
            "v1_3",
            "v1_3",
            "0",
            "-1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"L",
        "rotation":0,
        "sockets":[
            "4s",
            "-1",
            "-1",
            "v1_0",
            "2",
            "2f"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"L",
        "rotation":1,
        "sockets":[
            "2",
            "2f",
            "-1",
            "v1_1",
            "-1",
            "4s"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"L",
        "rotation":2,
        "sockets":[
            "-1",
            "4s",
            "-1",
            "v1_2",
            "2f",
            "2"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"L",
        "rotation":3,
        "sockets":[
            "2f",
            "2",
            "-1",
            "v1_3",
            "4s",
            "-1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"M",
        "rotation":0,
        "sockets":[
            "2",
            "-1",
            "-1",
            "v2_0",
            "-1",
            "1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"M",
        "rotation":1,
        "sockets":[
            "-1",
            "1",
            "-1",
            "v2_1",
            "-1",
            "2"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"M",
        "rotation":2,
        "sockets":[
            "-1",
            "2",
            "-1",
            "v2_2",
            "1",
            "-1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"M",
        "rotation":3,
        "sockets":[
            "1",
            "-1",
            "-1",
            "v2_3",
            "2",
            "-1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    },
    {
        "model":"Blank",
        "rotation":0,
        "sockets":[
            "-1",
            "-1",
            "-1",
            "-1",
            "-1",
            "-1"
        ],
        "posX":[],
        "negX":[],
        "posY":[],
        "negY":[],
        "posZ":[],
        "negZ":[]
    }
]